language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - phpunit --coverage-clover=coverage.clover --configuration ./phpunit.xml


after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover